DROP DATABASE IF EXISTS budget;

CREATE DATABASE budget;

USE budget;

DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS funds;

CREATE TABLE expenses (
  id INTEGER AUTO_INCREMENT,
  name VARCHAR(50),
  dollarVal INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE fundsLeft (
  id INTEGER AUTO_INCREMENT,
  amt INTEGER,
  PRIMARY KEY (id)
)